OrdererOrgs:
    - Name: Orderer
      Domain: test.com
      EnableNodeOUs: true
      Specs:
          - Hostname: orderer
            SANS:
                - localhost

# Definition of organizations managing peer nodes
PeerOrgs:
    - Name: Org1
      Domain: org1.test.com
      EnableNodeOUs: true # 节点组织单元
      Template:
          Count: 2
          SANS:
              - localhost # 好像是使用ssl的域名,证书中的域名(默认是Domain,如果使用localhost会ssl报错，所以需要加上)
          # Start: 0
          # Hostname: {{.Prefix}}{{.Index}} # default    peer0...
      # The number of user accounts _in addition_ to Admin
      Users:
          Count: 2
          SANS:
              - localhost

    - Name: Org2
      Domain: org2.test.com
      EnableNodeOUs: true
      Template:
          Count: 2
          SANS:
            - localhost
      Users:
          Count: 2
          SANS:
            - localhost
